AnyPageHead() ::= <<

<title>$page.og.title$</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<meta property="og:title" content="$page.og.title$"/>
<meta property="og:image" content="$page.og.image$"/>
<meta property="og:type" content="$page.og.type$"/>
<meta property="og:url" content="$page.og.url$"/>

<meta property="og:site_name" content="$page.og.siteName$"/>
<meta property="og:description" content="$page.og.description$"/>

<meta property="fb:app_id" content="$FacebookAppId()$"/>

>>