GuideLinks() ::= <<

<div class="hidden">
	<a class="guide" href="/guide/Guide01.html" title="Summary Period">Guide01</a>
	<a class="guide" href="/guide/Guide02.html" title="Groups of News">Guide02</a>
	<a class="guide" href="/guide/Guide03.html" title="Expanded Group">Guide03</a>
	<a class="guide" href="/guide/Guide04.html" title="All News in Group">Guide04</a>
	<a class="guide" href="/guide/Guide05.html" title="Customize Grouping">Guide05</a>
	<a class="guide" href="/guide/Guide06.html" title="Hidden Dimensions">Guide06</a>
	<a class="guide" href="/guide/Guide07.html" title="Search Box">Guide07</a>
	<a class="guide" href="/guide/Guide08.html" title="Top Bar">Guide08</a>
	<a class="guide" href="/guide/Guide09.html" title="Guide Complete">Guide09</a>
</div>

>>
