IntroPanel() ::= <<

<div id="introPanel" class="hidden">
	<div class="title">
		Welcome to <em>Readrz</em> &mdash; a search engine for news!
	</div>
	<div>
		Our design and summarization technique let you find any topic in a few clicks.
	</div>
	<div>
		We don't build your profile. You are in control. And you can find anything, fast.
	</div>
	<div>
		Please open our quick <em><a class="guideOpenLink">Guide</a></em> to make the most out of Readrz. 
		<em style="margin-left: 5px;"><a class="introCloseLink">[X] Close</a></em>
	</div>
</div>

>>