MyNewsInfo(page) ::= <<

<div class="myNewsInfo">

	<div class="title">
		Your Tabs
	</div>

	<div class="text">
		You can create your own tabs at Readrz!
	</div>
	<div class="text" style="padding-left: 25px; background-image: url(/img/star18_on.png);">
		Click star in any column (including search) to add it to your news
	</div>

	<div class="text">
		Please <a href="/login">Log in</a> or <a href="/register">Register</a> before you do that.
	</div>

	<div class="title">
		About Tabs
	</div>
	<div class="text">
		Every tab can contain many columns. Each column is defined by:
	</div>
	<div class="text" style="padding-left: 25px; background-image: url(/img/search18_on.png);">
		Search query &ndash; all news in the column much match (can be All)
	</div>
	<div class="text" style="padding-left: 25px; background-image: url(/img/filter18_on.png);">
		Filter &ndash; the way matching news should be filtered (Countries, etc)
	</div>
	<div class="text" style="padding-left: 25px; background-image: url(/img/period18_on.png);">
		Period &ndash; period for which the news should be summarized
	</div>
	<div class="text">
		The period selection cannot be saved for a specific column. 
		When you switch a column to another period, it's only 
		temporary.
		The period you select at the top is your main setting
		that applies to all columns when you change tabs.
	</div>
	
</div>

>>