page_share() ::= <<

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  
<head>
	<title>Share Readrz</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="stylesheet" type="text/css" href="/css/page.css">
	$HeadGoogleAnalytics()$
	$HeadFacebookInit()$
	$HeadTwitterInit()$
</head>

<body>

	<div>
		Thank You
	</div>
	<div class="more">
		Thanks a lot for sharing Readrz with your friends and followers!
	</div>
	<div>
		Facebook
	</div>
	<div class="more">
		<div class="fb-like" data-href="http://www.facebook.com/readrz" data-width="450" data-show-faces="true" data-send="true"></div>
	</div>
	<div>
		Twitter
	</div>
	<div class="more">
		<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.readrz.com" data-text="Readrz" data-via="readrz" data-size="large">Tweet</a>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
	</div>
	<div>
		Email
	</div>
	<div class="more">
		To send an email with a link to our website, please <a href="mailto:?subject=Readrz - Systematic News&body=I recommend you http://www.readrz.com - it's a great new website for exploring news" target="_new">click here</a>.
	</div>


</body>
</html>
>>