page_about() ::= <<

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  
<head>
	<title>About Readrz</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="stylesheet" type="text/css" href="/css/page.css">
	$HeadGoogleAnalytics()$
</head>

<body>

	<div>
		Problem
	</div>
	<div class="more">
		Many news reading apps have been created,
		but none let you explore all news systematically.
		The ones that pick the news for you, like Zite, suffer from the 
		<a href="http://dontbubble.us/" target="_blank">bubble syndrome</a>
		(you keep reading what you like, and you keep liking what you read).
		The ones that allow selecting your sources, like Pulse,  
		still overload you with information after you add more than a few sources. 
		The apps that employ user voting, like Reddit, suffer from a community bias.
		Currently no app, except Readrz, can summarize the news over 
		longer periods of time. People still buy Economist.
	</div>

	<div>
		Solution
	</div>
	<div class="more">
		Readrz analyzes and indexes the news using state-of-the-art linguistic algorithms. 
		It then allows you to slice and dice the news in a way that you are already used to, 
		similar to the tables of contents of the magazines and newspapers. 
		 
		Readrz calculates the best breakdown of news, optimizing the time you need to review them.
		The summary will depend on the period you select, allowing you to quickly overview all news 
		in a specific period of interest.
	</div>

	<div>
		Future
	</div>
	<div class="more">
		The algorithms we have designed are getting close (not quite, 
		but they are getting better and better) to what humans can do.
		We are investigating designing a similar search engine for other 
		areas like movies, books, corporate documents, etc.
		Here are some links if you want to follow the progress.
		Subscribe to our maling list using <a href="http://eepurl.com/d48hj" target="_new">this form</a>.
		Get in touch by email via <a href="mailto:andrey@readrz.com" target="_new">andrey@readrz.com</a>.
		You can also have a read through <a href="http://blog.readrz.com" target="_new">blog.readrz.com</a>.
	</div>

</body>
</html>
>>