page_terms() ::= <<

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  
<head>
	<title>Terms of Use</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="stylesheet" type="text/css" href="/css/page.css">
	$HeadGoogleAnalytics()$
</head>

<body>

<div>Website Usage Terms and Conditions</div>

<div class="more">Welcome to our website, Readrz.com. If you continue to browse and use this website, you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our privacy policy govern Readrz Ltd's relationship with you in relation to this website. If you disagree with any part of these terms and conditions, please do not use our website.</div>

<div class="more">The term 'Readrz Ltd' or 'us' or 'we' refers to the owner of the website whose registered office is Apartment 1604, 122 East Ferry Road, London E14 9FP, UK. Our company registration number is 07588147, and it is incorporated under the Companies Act 2006 as a private company with a registered office is in England and Wales. The term 'you' refers to the user or viewer of our website.</div>

<div class="more">The use of this website is subject to the following terms of use:</div>

<div class="more">
<ul>
<li>The content of the pages of this website is for your general information and use only. It is subject to change without notice.</li>
<li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</li>
<li>Your use of any information or materials on this website is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products, services or information available through this website meet your specific requirements.</li>
<li>This website contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance and graphics, as well as a proprietary algorithmic engine used to summarize the content. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions.</li>
<!-- li>All trademarks reproduced in this website, which are not the property of, or licensed to the operator, are acknowledged on the website.</li-->
<li>This website includes links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s).</li>
<li>This website uses cookies to identify returning visitors and remember which actions they have performed. By using this website you agree our cookies to be stored in your browser cache. These cookies do not contain your personal information.</li>
<li>Unauthorised use of this website may give rise to a claim for damages and/or be a criminal offence.</li>
<li>Your use of this website and any dispute arising out of such use of the website is subject to the laws of England, Northern Ireland, Scotland and Wales.</li>
</ul>
</div>

</body>
</html>
>>